name: photostock
services:
  api:
    image: photostock-api
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./photostock-api
      dockerfile: ./Dockerfile
    volumes:
      - ./volumes/chunks:/chunks
      - ./volumes/import:/import
      - ./volumes/library:/library
      - ./volumes/db:/db
    ports:
      - 4444:4444
  front:
    image: photostock-front
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./photostock-front
      dockerfile: ./Dockerfile
    ports:
      - 8888:80