name: photostock
networks:
  ${SUBNET_NAME}:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET_PART}.0.0/16
services:
  api:
    image: ghcr.io/djoulzy/photostock-api:main
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ./volumes/chunks:/chunks
      - ./volumes/import:/import
      - ./volumes/library:/library
      - ./volumes/assets:/assets
      - ./volumes/db:/db
    networks:
      ${SUBNET_NAME}:
        ipv4_address: ${SUBNET_PART}.0.10
    ports:
      - 4444:4444
  front:
    image: ghcr.io/djoulzy/photostock-front:main
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      ${SUBNET_NAME}:
        ipv4_address: ${SUBNET_PART}.0.11
    ports:
      - ${APP_PORT}:80